version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.17.4
    volumes:
      - ./elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker_volumes/elasticsearch/data:/var/lib/elasticsearch/data
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:7.17.4
    volumes:
      - ./elk/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5555:5555"
      - "9600:9600"
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.17.4
    volumes:
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  default:
    name: chatbot_mark-app-network

volumes:
  elasticsearch:
